[package]
name = "rsgb-jit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Cranelift JIT backend for rsgb programs"

[dependencies]
rsgb.workspace = true
rustc-hash.workspace = true
rayon.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-native.workspace = true

[dev-dependencies]
rsgb = { workspace = true, features = ["synth"] }

[lints]
workspace = true
